-- Simple Query with 1 Virtual Table
SELECT * FROM USER999.AWS_ACCOUNTS;

-- Simple Query with 1 Join View Virtual Table 
SELECT * FROM USER999."JV-AWS_CUSTOMER_PROFILE-ES_STOCK_TRANSACTIONS"
ORDER BY TX_DATE DESC;

-- Simple Query Joining 2 Virtual Tables 
SELECT A.CUSTID, STH.TX_DATE, STH.SYMBOL, STH.PRICE, STH.QUANTITY
FROM AWS_ACCOUNTS A 
INNER JOIN HDP_STOCK_TRANSACTIONS STH ON A.CUSTID = STH.CUSTID
WHERE A.CUSTID = 108277
ORDER BY STH.QUANTITY DESC;